const ADD_OPERATOR = '+'
const SUB_OPERATOR = '-'
const MUL_OPERATOR = '*'
const DIV_OPERATOR = '/'
const MODULO_OPERATOR = '%'

exports.ADD_OP = ADD_OPERATOR
exports.SUB_OP = SUB_OPERATOR
exports.MUL_OP = MUL_OPERATOR
exports.DIV_OP = DIV_OPERATOR
exports.MOD_OP = MODULO_OPERATOR